/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Reply = IDL.Record({ 'message' : IDL.Text, 'timestamp' : Time });
export const ReplyPayload = IDL.Record({ 'message' : IDL.Text });

export const idlService = IDL.Service({
  'getAllReplies' : IDL.Func([], [IDL.Vec(Reply)], ['query']),
  'getReply' : IDL.Func([Time], [Reply], ['query']),
  'submitReply' : IDL.Func([ReplyPayload], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Reply = IDL.Record({ 'message' : IDL.Text, 'timestamp' : Time });
  const ReplyPayload = IDL.Record({ 'message' : IDL.Text });
  
  return IDL.Service({
    'getAllReplies' : IDL.Func([], [IDL.Vec(Reply)], ['query']),
    'getReply' : IDL.Func([Time], [Reply], ['query']),
    'submitReply' : IDL.Func([ReplyPayload], [], []),
  });
};

export const init = ({ IDL }) => { return []; };